=== IanMadlenya/industry-classification-lookup/documentation/schemas/sic-search-response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "SIC Search",
  "type": "object",
  "required": ["numFound", "nonFilteredFound", "results"],
  "properties": {
    "numFound": {
      "description": "The number of results found for this search.",
      "type": "number"
    },
    "nonFilteredFound": {
      "description": "The number of results found, excluding any filtering appled for sectors.",
      "type": "integer"
    },
    "results": {
      "description": "The actual results of the search.",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["code", "desc"],
        "properties": {
          "code": {
            "description": "Unique code for the industry classification",
            "type": "string",
            "pattern": "^[0-9]{1,5}$"
          },
          "desc": {
            "description": "Description of the industry classification",
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "sectors": {
      "description": "The sectors found for the search results, to enable filtering of results.",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["code", "name", "count"],
        "properties": {
          "code": {
            "description": "Unique code for the industry sector",
            "type": "string",
            "pattern": "^[A-Z]$"
          },
          "name": {
            "description": "The human readable name of the sector",
            "type": "string"
          },
          "count": {
            "description": "The number of results in this sector",
            "type": "integer"
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== IanMadlenya/industry-classification-lookup/documentation/examples/sic-search-example2.json
{
  "numFound": 27,
  "nonFilteredFound": 27,
  "results": [
    {
      "code": "01410",
      "desc": "Dairy farming"
    },
    {
      "code": "01430",
      "desc": "Stud farming"
    },
    {
      "code": "01450",
      "desc": "Goat farming"
    },
    {
      "code": "01450",
      "desc": "Sheep farming"
    },
    {
      "code": "01460",
      "desc": "Pig farming"
    }
  ],
  "sectors": [
    {
      "code": "A",
      "name": "Agriculture, Forestry And Fishing",
      "count": 27
    }
  ]
}

=== IanMadlenya/industry-classification-lookup/documentation/examples/sic-search-example3.json
{
  "numFound": 67,
  "nonFilteredFound": 67,
  "results": [
    {
      "code": "26200",
      "desc": "Computer (manufacture)"
    },
    {
      "code": "85590",
      "desc": "Computer training"
    },
    {
      "code": "18203",
      "desc": "Reproduction of computer media"
    },
    {
      "code": "26200",
      "desc": "Analogue computer (manufacture)"
    },
    {
      "code": "26200",
      "desc": "Computer (electronic) (manufacture)"
    }
  ],
  "sectors": [
    {
      "code": "C",
      "name": "Manufacturing",
      "count": 26
    },
    {
      "code": "J",
      "name": "Information And Communication",
      "count": 18
    },
    {
      "code": "G",
      "name": "Wholesale And Retail Trade; Repair Of Motor Vehicles And Motorcycles",
      "count": 8
    },
    {
      "code": "S",
      "name": "Other Service Activities",
      "count": 7
    },
    {
      "code": "F",
      "name": "Construction",
      "count": 4
    },
    {
      "code": "P",
      "name": "Education",
      "count": 2
    },
    {
      "code": "M",
      "name": "Professional, Scientific And Technical Activities",
      "count": 1
    },
    {
      "code": "N",
      "name": "Administrative And Support Service Activities",
      "count": 1
    }
  ]
}
